name: flu_fire_auth
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  fluttericon: ^2.0.0
  animations: ^2.0.1
  lottie: ^1.1.0
  bloc: ^7.1.0
  flutter_bloc: ^7.2.0
  equatable: ^2.0.3
  # Route and Dependency management
  flutter_modular: ^4.0.0+6
  event_bus: ^2.0.0
  get_it: ^7.2.0
  http: ^0.13.3
  flow_builder: ^0.0.4
  shared_preferences: ^2.0.7
  flutter_easyloading: ^3.0.3
  url_launcher: ^6.0.10
  connectivity_plus: ^1.1.0
  bottom_navy_bar: ^6.0.0
  awesome_dialog: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_native_splash: ^1.2.3


flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/icons/
    - assets/lotties/
